# Compose specification

x-php-service: &php-service
  build:
    context: ./docker/php
  volumes:
    - .:/var/www/html

x-mariadb_service: &mariadb_service
  image: mariadb:latest
  environment: &db-environment
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  healthcheck:
    test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
    interval: 10s
    timeout: 5s
    retries: 5

services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - '9100:9000'
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=${SONAR_JDBC_PASSWORD}
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: sonarqube_postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=${POSTGRES_PASSWORD}
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

  php:
    <<: *php-service
    container_name: php
    ports:
      - '9001:9000'
    environment:
      - APP_ENV=development
      - LLM_API_URL:"http://ollama:11434"
    networks:
      - app-network
    depends_on:
      - ollama
      - node
    volumes:
      - .:/var/www/html

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    environment:
      - APP_ENV=development
    networks:
      - app-network

  mariadb:
    <<: *mariadb_service
    container_name: mariadb
    environment:
      <<: *db-environment
      MYSQL_DATABASE: barkochba
      MYSQL_USER: game
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  node:
    image: node:20-slim
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: npm install

  dbmate:
    image: amacneil/dbmate
    environment:
      - DATABASE_URL=mysql://game:${MYSQL_PASSWORD}@mariadb:3306/barkochba
    command: up
    volumes:
      - ./src/Storage/Migrations:/db/migrations
    depends_on:
      - mariadb

volumes:
  db_data: {}
  ollama_data: {}
  sonarqube_data: {}
  sonarqube_extendsions: {}
  sonarqube_logs: {}
  postgresql_data: {}
networks:
  app-network:
